import type { Topic } from '../types'

function escapeXml(s: string): string {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;')
}

function topicToFreeMind(topic: Topic, depth: number): string {
  const indent = '  '.repeat(depth)
  const escaped = escapeXml(topic.title)
  let xml = `${indent}<node TEXT="${escaped}"`

  if (topic.folded) {
    xml += ' FOLDED="true"'
  }

  if (topic.children && topic.children.length > 0) {
    xml += '>\n'
    for (const child of topic.children) {
      xml += topicToFreeMind(child, depth + 1)
    }
    xml += `${indent}</node>\n`
  } else {
    xml += ' />\n'
  }

  return xml
}

export function exportToFreeMind(root: Topic): string {
  const escaped = escapeXml(root.title)
  return `<?xml version="1.0" encoding="UTF-8"?>
<map version="1.0.1">
<!-- Generated by Gmind -->
<node TEXT="${escaped}">
${(root.children || []).map(c => topicToFreeMind(c, 2)).join('')}</node>
</map>
`
}

export function downloadFreeMind(content: string, filename: string) {
  const blob = new Blob([content], { type: 'application/xml;charset=utf-8' })
  const a = document.createElement('a')
  a.href = URL.createObjectURL(blob)
  a.download = filename
  a.click()
  URL.revokeObjectURL(a.href)
}
